#!/usr/bin/env node
// The design-sync "build" for this repo. The site is a Next.js app, not a
// library: it has no dist/ and no shipped .d.ts tree, and the converter reads
// the component API from a .d.ts tree. This emits one with the repo's own
// tsc, into the gitignored .design-sync/.cache/dts/, and writes the barrel
// (index.d.ts) that package.json `types` points at.
//
//   node .design-sync/build-dts.mjs
//
// Steps: tsc --emitDeclarationOnly (tsconfig.dts.json) -> rewrite `@/…`
// aliases to relative paths (the converter's checker has no `paths`) ->
// move the dot-directory output (.design-sync/) to design-sync/ so the
// converter's glob sees it -> write index.d.ts.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const OUT = join(HERE, '.cache', 'dts');
const tsc = join(ROOT, 'node_modules', '.bin', 'tsc');

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
try {
  execFileSync(tsc, ['-p', join(HERE, 'tsconfig.dts.json')], { stdio: 'inherit', cwd: ROOT });
} catch (e) {
  console.error('[build-dts] tsc reported errors — declarations were still emitted; fix the errors above before trusting the API surface');
  if (!existsSync(join(OUT, 'components'))) process.exit(1);
}

const walk = (d) => readdirSync(d).flatMap((n) => {
  const p = join(d, n);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

// The converter's glob skips dot-directories: surface .design-sync/ as design-sync/.
const dotDir = join(OUT, '.design-sync');
const plainDir = join(OUT, 'design-sync');
if (existsSync(dotDir)) renameSync(dotDir, plainDir);

// Rewrite `@/x` (repo-root alias) to a path relative to the emitted file.
let rewrites = 0;
for (const f of walk(OUT).filter((p) => p.endsWith('.d.ts'))) {
  const src = readFileSync(f, 'utf8');
  const next = src.replace(/(['"])@\/([^'"]+)\1/g, (_, q, tail) => {
    let rel = relative(dirname(f), join(OUT, tail)).split('\\').join('/');
    if (!rel.startsWith('.')) rel = `./${rel}`;
    rewrites++;
    return `${q}${rel}${q}`;
  });
  if (next !== src) writeFileSync(f, next);
}

// Barrel: every component module (mirrors the converter's synthesized entry)
// plus the design-sync entry (default-export re-exports, PageGround).
const compDir = join(OUT, 'components');
const modules = walk(compDir)
  .filter((p) => p.endsWith('.d.ts') && !/\.(test|spec|stories)\./.test(p))
  .map((p) => './' + relative(OUT, p).split('\\').join('/').replace(/\.d\.ts$/, ''))
  .sort();
const entryDts = join(plainDir, 'entry.d.ts');
const lines = [
  '// Generated by .design-sync/build-dts.mjs — the API surface the design build reads.',
  ...modules.map((m) => `export * from '${m}';`),
  ...(existsSync(entryDts) ? [`export * from './design-sync/entry';`] : []),
];
writeFileSync(join(OUT, 'index.d.ts'), lines.join('\n') + '\n');
console.error(`[build-dts] ${modules.length} component modules, ${rewrites} alias rewrites → ${relative(ROOT, OUT)}/index.d.ts`);
