// SessionsData.jsx — single source of truth for upcoming + past sessions.
// Drop-in for Claude Code: this shape maps 1:1 to a Notion DB or MDX frontmatter.
// Fields: slug, date (ISO), time, tz, host, hostRole, hostPortrait, theme, blurb,
//         format, durationMin, seats, seatsLeft, price, status, tags, replay,
//         isGuestStage (true = Wed Guest Stage £25 sliding | false/undefined = Tue regular £10).
//
// Canonical reference: see "Loop Breakers - Source of Truth.html" (project root)
// — this file is DERIVED from §02 §03 §04 of that doc.

window.SESSIONS = [
  // ─── Tue 5 May 2026 — FIRST LOOP BREAKERS ──────────────────────────────
  {
    slug: "may-2026-first-loop-breakers",
    date: "2026-05-05",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "The first Loop Breakers.",
    blurb: "Bring one idea you've been circling. We'll shrink it until it's launchable. Small, slow, held — the room I wish I'd had.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 9,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "open",
    tags: ["Founders", "Launch", "First session"],
    accent: "#38ff99",
  },

  // ─── Tue 12 May ────────────────────────────────────────────────────────
  {
    slug: "may-2026-week-2",
    date: "2026-05-12",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "What's looping for you?",
    blurb: "Same room, week two. Bring whatever's still circling. We'll move it forward by one step — that's the whole goal.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "open",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Tue 19 May ────────────────────────────────────────────────────────
  {
    slug: "may-2026-week-3",
    date: "2026-05-19",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "Move one idea forward.",
    blurb: "Loop Breakers regular. Ninety minutes. One small clear next step. The day before our first Guest Stage with Nicki Hambleton.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Wed 20 May — GUEST STAGE · NICKI HAMBLETON ────────────────────────
  {
    slug: "may-2026-guest-stage-nicki-hambleton",
    date: "2026-05-20",
    time: "10:30",
    tz: "BST",
    host: "Nicki Hambleton",
    hostRole: "Apple Distinguished Educator · illustrator · first Guest Stage",
    hostPortrait: null,
    theme: "Drawing as thinking. Sketch-noting for stuck ideas.",
    blurb: "Off-cadence Wednesday. Our first Guest Stage. Nicki on drawing as a thinking tool — talk plus held Q&A. No skill level required. Bring a pen and one tangle.",
    format: "Online · Guest Stage · Zoom",
    durationMin: 90,
    seats: 40, seatsLeft: 40,
    isGuestStage: true,
    price: { amount: 25, currency: "£", note: "Sliding £15 / £25 / £40 — pick at checkout", sliding: true, slidingTiers: [15, 25, 40] },
    status: "soon",
    tags: ["Guest Stage", "Visual thinking", "Creativity"],
    accent: "#db7dcc",
  },

  // ─── Tue 26 May ────────────────────────────────────────────────────────
  {
    slug: "may-2026-week-4",
    date: "2026-05-26",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "After Nicki — what now?",
    blurb: "First Tuesday after the Guest Stage. Bring whatever Nicki shook loose, or the thing you've been circling all along. Either is welcome.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Tue 2 Jun ─────────────────────────────────────────────────────────
  {
    slug: "jun-2026-week-1",
    date: "2026-06-02",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "Pricing the thing when your nervous system says 'ask for less'.",
    blurb: "For neurodivergent founders who chronically under-price. One session, one number you'll actually say out loud by the end.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Pricing", "Founders"],
    accent: "#ff8a1c",
  },

  // ─── Tue 9 Jun ─────────────────────────────────────────────────────────
  {
    slug: "jun-2026-week-2",
    date: "2026-06-09",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "What's still looping?",
    blurb: "Loop Breakers regular. The room is the room — bring what's stuck, leave with one step.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Tue 16 Jun ────────────────────────────────────────────────────────
  {
    slug: "jun-2026-week-3",
    date: "2026-06-16",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "The half-finished thing.",
    blurb: "Bring the project that's 60% done and won't move. We'll find the actual blocker — usually not the one you thought.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Tue 23 Jun ────────────────────────────────────────────────────────
  {
    slug: "jun-2026-week-4",
    date: "2026-06-23",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "An idea you haven't said out loud yet.",
    blurb: "If you've been carrying a quiet thing — bring it. The cost of saying it in this room is low. The cost of carrying it for another year is higher than you think.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Tue 30 Jun ────────────────────────────────────────────────────────
  {
    slug: "jun-2026-week-5",
    date: "2026-06-30",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "Mid-year reset.",
    blurb: "Half the year is gone. The other half is still here. One session, one honest look at what to drop and what to keep going on.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Tue 7 Jul ─────────────────────────────────────────────────────────
  {
    slug: "jul-2026-week-1",
    date: "2026-07-07",
    time: "10:30",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "Nine weeks in.",
    blurb: "If you've been to a few of these, you'll know the rhythm. If it's your first — welcome. The format works either way.",
    format: "Online · Loop Breakers (regular) · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 10,
    isGuestStage: false,
    price: { amount: 10, currency: "£", note: "One-off · £5 access seat on request", sliding: false },
    status: "soon",
    tags: ["Founders"],
    accent: "#69d9d1",
  },

  // ─── Past — Apr 2026 prototype ─────────────────────────────────────────
  {
    slug: "apr-2026-first-loop",
    date: "2026-04-16",
    time: "19:00",
    tz: "BST",
    host: "Nici Foote",
    hostRole: "Founder, Unbarrier",
    hostPortrait: "../../assets/nici-portrait-circle-green.png",
    theme: "The very first Loop Breakers.",
    blurb: "Where it started. A prototype room of eight women with one idea each and a ninety-minute container. Pre-launch run.",
    format: "Online · prototype · Google Meet",
    durationMin: 90,
    seats: 10, seatsLeft: 0,
    isGuestStage: false,
    price: { amount: 0, currency: "£", note: "Pre-launch · invite only", sliding: false },
    status: "past",
    tags: ["Archive"],
    accent: "#ffc203",
    replay: false,
  },
];
